name: Run FastAPI server for 20 minutes

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the server on'
        required: true
        default: 'main'

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Start hosting
      uses: 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        nohup uvicorn nook.functions.viewer.viewer:app --host 0.0.0.0 --port 8000 &
        sleep 1200  # Run for 20 minutes (1200 seconds)
