name: Run main.py in Container

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule: # Runs the workflow periodically
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    services:
      docker:
        image: python:3.9
        options: --user 1001

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Clone nook repository
      run: git clone https://github.com/masahito-uwamichi/nook.git

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r nook/requirements.txt
        pip install -r nook/requirements-dev.txt

    - name: Run script
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}=
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        OUTPUT_DIR: "${{ github.workspace }}/output"
      run: |
        python main.py
